import type {NextPage} from 'next'
import Head from 'next/head'
import requireAuthentication from '../server/common/requireAuthentication'
import Navbar from '../components/navbar'
import PostBox from '../components/postbox'
import PostFeed from '../components/postfeed'

const Index: NextPage = () => {
    return (
        <>
            <Head>
                <title>Create T3 App</title>
                <meta name="description" content="Generated by create-t3-app"/>
                <link rel="icon" href="/favicon.ico"/>
            </Head>

            <Navbar/>
            <main className="bg-gray-50 dark:bg-gray-600">
                <div
                    className=" container mx-auto max-w-7xl flex flex-col items-center justify-start min-h-screen py-4 px-8">
                    <PostBox/>
                    <PostFeed/>
                </div>
            </main>
        </>
    )
}

export const getServerSideProps = requireAuthentication()

export default Index
